### PR TITLE
fix: delegated calls support

### LINKED ISSUE #131: fix: support faking and mocking delegated calls
**Describe the bug**
Smock currently does not support any interaction with delegated calls.

**Reproduction steps**

1. Create a Proxy contract
1. Fake a fake using an interface of a contract with the function `foo`
1. Force the fake to return `true` when the function `foo` is called
1. Call the method `foo` of the fake through the proxy
1. Expect to receive `true`

**Expected behavior**
Be able to work with mock and fakes when using delegated calls.

As well, it would be great to have a way to assert that a call to a function was delegated from address 0x123.

### PR DESCRIPTION
**Pull request by 0xGorilla**
**Description**
Fixes #131

* Adds support to delegated calls in both fakes and mocks
* Adds custom assertion `expect(myFake.myFunction).to.be.delegatedFrom(myProxy.address)`

Canary version: 0.0.0-9be6e836

### CODE REVIEW

File: src/factories/smock-contract.ts [hunk 1]
```diff
@@ -199,7 +202,8 @@ function parseMessage(message: Message, contractInterface: Interface, sighash: s
   return {
     args: sighash === null ? toHexString(message.data) : getMessageArgs(message.data, contractInterface, sighash),
     nonce: Sandbox.getNextNonce(),
-    target: fromFancyAddress(message.delegatecall ? message._codeAddress : message.to),
+    target: fromFancyAddress(message.delegatecall ? message.codeAddress : message.to),
```
Comment (wei3erHase) [inline src/factories/smock-contract.ts:205]: why the change in `_codeAddress` vs `codeAddress`?

File: test/unit/watchable-function-logic/misc.spec.ts [hunk 2]
```diff
@@ -30,4 +30,10 @@ describe('WatchableFunctionLogic: Miscellaneous', () => {
       fake.receiveBoolean.should.always.have.been.calledOnceWith(true);
     }).to.throw('always flag is not supported for method calledOnceWith');
   });
+
+  it('should throw when expecting a delegatedFrom that did not happen', async () => {
+    expect(() => {
+      fake.receiveBoolean.should.to.be.delegatedFrom(fake.address);
```
Comment (wei3erHase) [inline test/unit/watchable-function-logic/misc.spec.ts:36]: is the `.to.be` necessary or can we just use `should.be`?

File: src/factories/smock-contract.ts (hunk 1 above)
Comment (0xGorilla) [reply src/factories/smock-contract.ts:205]: same value actually. Just thought it was nicer

File: test/unit/watchable-function-logic/misc.spec.ts (hunk 2 above)
Comment (0xGorilla) [reply test/unit/watchable-function-logic/misc.spec.ts:36]: pushed `should.be`

File: docs/source/fakes.rst [hunk 3]
```diff
@@ -371,3 +371,17 @@ Modifying the :code:`receive` function
 .. code-block:: typescript
 
   myFake.receive.returns();
+
+Delegated calls
```
Comment (hickscorp) [inline docs/source/fakes.rst:375]: I would strongly suggest adding a paragraph or two around Diamonds, as it might not be obvious to everyone. Something like:

```
If you're using the diamond pattern ([EIP-2535](https://eips.ethereum.org/EIPS/eip-2535)), you can use Smock to ensure that certain facets of your diamond are being called by others.

To do so, you can simply perform a DiamondCut operation, replacing one of your facets by a fake or a mock. It could look like something like this in your setup:

```typescript
const sigsFromABI = (abi: any[]): string[] =>
  abi
    .filter(frag => frag.type === 'function')
    .map(frag => Interface.getSighash(FunctionFragment.from(frag)));


myFacetFake = await smock.fake('MyFacet');

const selectors = sigsFromABI((await artifacts.readArtifact('MyFacet')).abi);
const diamond = await ethers.getContract('OurDiamond');
await diamond.diamondCut([{
  facetAddress: myFacetFake.address,
  action: FacetCutAction.Replace,
  functionSelectors: selectors
}], ZERO_ADDRESS, '0x')
```

This replaces `MyFacet`'s address from your diamond proxy with the address of your fake facet.

Alternatively, you could also decide to directly to deploy your diamond without `MyFacet` and perform a DiamondCut specifying the `FacetCutAction.Add` instead of `FacetCutAction.Replace`.

Afterwards, testing that a given facet is being called by another becomes simple. For example if the facet you're testing has a `foo(string memory message)` method that in turns calls `MyFacet(address(this)).bar(message)`, you can test that `MyFacet.bar` is called:

```ts
        await diamond.foo('Whatever');
        expect(myFacetFake.bar).to.have.been
          .calledWith('Whatever)
          .delegatedFrom(diamond.address);
```

**Review by hickscorp — APPROVED** [review]

**Comment by hickscorp** [comment]
FWIW: I've gone through this PR, but I've also tested it using a companion project located [right here](https://github.com/hickscorp/smock-diamond-showcase).

The sample project exhibits how to use Smock along with the Diamond pattern to test that facets are being called.
It also uses `hardhat-deploy` fixtures to make sure that both modes function properly.

File: docs/source/fakes.rst (hunk 3 above)
Comment (0xGorilla) [reply docs/source/fakes.rst:375]: Will do in a separate PR
